### ISSUE TITLE
can there be a way to line up the layers. feature request.

### ISSUE THREAD

**Issue by gsgoldma** [KohakuBlueleaf/a1111-sd-webui-haku-img#1]
so for instance, if i want to put a shirt on someone, I could line up the shirt with the person's body, with resizing and centering.

**Comment by KohakuBlueleaf** [comment]
I will try to do something like that but it is limited by gradio itself so it's hard to impl this

**Comment by KohakuBlueleaf** [comment]
And if you have any idea to do this thing
Feel free to make PR!

**Comment by KohakuBlueleaf** [comment]
I think this need extra utils
I will close it at first since I have no plan to use non-gradio things.
After sd-webui dumps to gradio 4 I may start making few custom components which are good for this
