### ISSUE TITLE
Will only work in Python 3.10+

### ISSUE THREAD

**Issue by lbeltrame** [KohakuBlueleaf/a1111-sd-webui-haku-img#11]
Hello,

currently this extensions uses features that are available only in Python 3.10 (such as | for typing). 
This leaves out a chunk of cloud users (Colab and Paperspace) which use 3.8 and 3.9, respectively.

This traceback is produced on startup (from Paperspace, which uses 3.9):

```
Error executing callback ui_tabs_callback for /notebooks/stable-diffusion-webui/extensions/a1111-sd-webui-haku-img/scripts/main.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/script_callbacks.py", line 106, in ui_tabs_callback
    res += c.callback() or []
  File "/notebooks/stable-diffusion-webui/extensions/a1111-sd-webui-haku-img/scripts/main.py", line 211, in add_tab
    component.change(pixel.run, all_p_input, image_out)
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 81, in change
    dep = self.set_event_trigger(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 190, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "/usr/local/lib/python3.9/dist-packages/gradio/utils.py", line 787, in check_function_inputs_match
    parameter_types = typing.get_type_hints(fn) if inspect.isfunction(fn) else {}
  File "/usr/lib/python3.9/typing.py", line 1497, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by KohakuBlueleaf** [comment]
I'm considering about this.
Perseonally I don't want to drop any useful features in py3.10 just for compability.
But I know it's very hard to use py3.10 on colab or other cloud platform...

**Comment by R-N** [comment]
> I'm considering about this. Perseonally I don't want to drop any useful features in py3.10 just for compability. But I know it's very hard to use py3.10 on colab or other cloud platform...

Is the typing module not good enough? (Not passive aggressive I genuinely don't know if it can fully do what py3.10 hints do)
[Ref](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/pull/3)

**Comment by KohakuBlueleaf** [comment]
@R-N I mean, I am also using something like pattern matching.

**Comment by KohakuBlueleaf** [comment]
I can use typing module to do typing and remove the pattern matching from what I'm doing.
but I need to say this action is very counterintuitive for me.

Upgrade for Downgrade

**Comment by KohakuBlueleaf** [comment]
@R-N I push a commit for this.
Should work?

**Comment by lbeltrame** [comment]
For me it seems to.

**Comment by KohakuBlueleaf** [comment]
@lbeltrame so now it can work?
or some new error(

**Comment by Karakor23** [comment]
Please, using a script to put the colab in 3.10 doesnt seem to work either. There is an issue with Xformers. :(

**Comment by KohakuBlueleaf** [comment]
@Karakor23 I already push a commit for this
please check if it works

**Comment by lbeltrame** [comment]
No more error for me. But that was since the first commit you made to address the issue.

**Comment by Karakor23** [comment]
Still an issue, https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/midjourney_v4_diffusion_webui_colab.ipynb is wha tI am using

**Comment by Karakor23** [comment]
works
