### ISSUE TITLE
a way to refresh the effects sliders

### ISSUE THREAD

**Issue by gsgoldma** [KohakuBlueleaf/a1111-sd-webui-haku-img#12]
i found that if i put another image into it, the same settings are leftover from the last image. it'd be cool if there was a way to reset them back to default. would help if you messed up a setting and forgot which one, without refreshing the browser.

**Comment by KohakuBlueleaf** [comment]
doing it

**Comment by KohakuBlueleaf** [comment]
@gsgoldma I add reset btn for Color/Tone Curve/Sketch/Pixelize/Glow
Please check it

**Comment by gsgoldma** [comment]
thannk

> @gsgoldma I add reset btn for Color/Tone Curve/Sketch/Pixelize/Glow Please check it

thanks ! it works great! really appreciate your work, it's a very useful extension
