### ISSUE TITLE
solo layers

### ISSUE THREAD

**Issue by vis223** [KohakuBlueleaf/a1111-sd-webui-haku-img#14]
If I want to check what is on a layer I have to go to all layers above it and turn down their opacity. Unless I am missing something, this seems like a really long way to do things.
Is there a way to isolate layers more quickly? Perhaps a check on/off for each layer? Maybe even a quick way re-order them.
I can see how this could be the most useful and creative extension of auto111. Finally, a way to bash countless variations is genius, but presently I get so confused trying to work out what order I should be masking while remembering what's on each layer. I end up randomly clicking and sliding out of frustration.
I've watched your videos a ton but I just can't work it out so my best hope is a you-tuber does an in-depth explainer on this amazing ext.
There's been a ton of updates since I last tried this so I have no doubts about where it's heading.   it's setting up to be pretty awesome. Well done, keep up; the good work

**Comment by KohakuBlueleaf** [comment]
@vis223 thank for your feedback!
I will add some way to reorder (maybe move up/down button) of every layer and mute/solo btn like some DAW doing
But I need to do some custom item for this thing
You may need to wait for a while

**Comment by KohakuBlueleaf** [comment]
And about exaplaining this extension
I'm plaing to make a video on it.
Maybe by my self XD or invite some youtuber to do this on it.

**Comment by KohakuBlueleaf** [comment]
Gradio 4 looks like have built-in layer feature
Will wait until a41 update to gradio 4 and try to adapt them.
