### ISSUE TITLE
error if trying to use on vlad's fork of automatic

### ISSUE THREAD

**Issue by gsgoldma** [KohakuBlueleaf/a1111-sd-webui-haku-img#15]
executing callback: D:\automatic\extensions\a1111-sd-webui-haku-img\scripts\main.py ui_tabs_callback: UnboundLocalError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\script_callbacks.py:142 in ui_tabs_callback                                                    │
│                                                                                                                     │
│   141 │   │   try:                                                                                                  │
│ > 142 │   │   │   res += c.callback() or []                                                                         │
│   143 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ D:\automatic\extensions\a1111-sd-webui-haku-img\scripts\main.py:314 in add_tab                                      │
│                                                                                                                     │
│   313 │   │   gpc.bind_buttons(send_btns, image_out, None)                                                          │
│ > 314 │   │   for btn, img in zip(btns, all_layers):                                                                │
│   315 │   │   │   btn.click(lambda x:x, image_out, img)                                                             │
└─────────────────────────────────────────────────────────────
UnboundLocalError: local variable 'btns' referenced before assignment

**Comment by brunogcar** [comment]
https://github.com/vladmandic/automatic/issues/840#issuecomment-1543048656 

is extension going to be updated to support both a1111 and vlad  repos with out hard coded label names?

cos this is a great extension,  really useful but many ppl are switching to vlad due to various a1111 issues over the time and i personally think it is one of a few things i miss from using a1111

**Comment by KohakuBlueleaf** [comment]
@brunogcar I push a temporary fix which use elem id instead of label to determine which component is we need.
It should work for both a41 and vlad
but only for now.

**Comment by brunogcar** [comment]
@KohakuBlueleaf  yeap,  temp fix  did it

as far as im concerned you can close this issue, unless you want to keep it opened to remind you to do  something else, 

thanks
