### ISSUE TITLE
"Other" tab: some suggestions

### ISSUE THREAD

**Issue by IPv6** [KohakuBlueleaf/a1111-sd-webui-haku-img#17]
Please, add feature "Set size X/Y aligning to top/left/right/bottom", upscaling/downscaling image (no fancy stuff, PIL resize) to fit final size. This tab useful for preparing image for inpaint and there is no point in calculating exact values in that case
Tnx for the tool!

**Comment by KohakuBlueleaf** [comment]
@IPv6 upscale/downscale is easy and I can actually combine my another IR/SR repo
the problem is can you give me some example(like input w*h, set what, get what)
I cannot get your request very clearly
sry

**Comment by IPv6** [comment]
@KohakuBlueleaf 

I am talking about tab with fields:

Final size: [...W...] x [...H...]
Original image align: *Top   *Bottom  *Left *Right
Button [Resize]

Resize should resize initial image to fit W*H and fill any empty areas according to align and initial-final aspect difference

**Comment by KohakuBlueleaf** [comment]
OK I know what you want to do,
will do that
(And sry for late response)

**Comment by KohakuBlueleaf** [comment]
@IPv6 Done it
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-haku-img/assets/59680068/74cbe399-3124-4554-8948-078ea2f826bb)

If you think the old one should be preserved I will add it back as a new page under inoutpaint
