### ISSUE TITLE
[Feature Request] Pixelizer

### ISSUE THREAD

**Issue by ClashSAN** [KohakuBlueleaf/a1111-sd-webui-haku-img#3]
https://github.com/C10udburst/stable-diffusion-webui-scripts
![00073-2522166635-](https://user-images.githubusercontent.com/98228077/213501149-5843b9fe-3f48-4cd4-ac86-c1e1b798e7b9.png)
![00062-2522166635-an sks kirby protagonist by the beach](https://user-images.githubusercontent.com/98228077/213501160-285c2493-e53f-49fd-b6ed-b2f80bc856eb.png)

**Comment by KohakuBlueleaf** [comment]
Oh yes! pixelart is a good feature to add.
BTW I already has python impl to do this thing so just wait me a min to add this
https://pixelgen.kblueleaf.net/

**Comment by KohakuBlueleaf** [comment]
@ClashSAN 
![image](https://user-images.githubusercontent.com/59680068/213517886-91c72c4f-3cea-44f4-a098-ed85a99548c5.png)

I think this is what you want?

**Comment by ClashSAN** [comment]
Wow, you did this in 30 minutes. :D

**Comment by KohakuBlueleaf** [comment]
I just reuse code in this repo XD:
https://github.com/KohakuBlueleaf/PixelGen

**Comment by KohakuBlueleaf** [comment]
@ClashSAN I have add different algo for pixelizer, like dithering thing.
I think you will be interested in it!

for example:
![image](https://user-images.githubusercontent.com/59680068/214216369-6e2b6159-e714-4f64-9d18-48259af0b0fc.png)
