### ISSUE TITLE
button

### ISSUE THREAD

**Issue by 4lt3r3go** [KohakuBlueleaf/a1111-sd-webui-haku-img#34]
please brother, consider adding a "SAVE" button to allow save in the selected folder according to Auto1111 settings and image format settings. I'm using this beautiful extention everyday but i'm always forced to send the image to img1img module, denoise 0 and then save again, to allow actual save to jpg/png, also with metadata.

**Comment by 4lt3r3go** [comment]
:(

**Comment by 4lt3r3go** [comment]
no news?
this extention is really great and could save tons of time if only had a save button and avoid removing the metadata prompt bounded in the images. 
I was using it everyday but unfortunatly i had to switch back to photoshop and topaz.

**Comment by KohakuBlueleaf** [comment]
> no news? this extention is really great and could save tons of time if only had a save button and avoid removing the metadata prompt bounded in the images. I was using it everyday but unfortunatly i had to switch back to photoshop and topaz.

News here
I finally finish this semester and will go back for this extension soon

I will also bring something new like better pixelization method.

**Comment by KohakuBlueleaf** [comment]
SAVE feature will be added soon
within 48hours.

**Comment by KohakuBlueleaf** [comment]
@4lt3r3go Save button added
I will investigate how to adapt original png info and append new info on it.
currently you need to use custom exif to write the info you want to save
