### ISSUE TITLE
Can't use it error

### ISSUE THREAD

**Issue by umairsali07** [KohakuBlueleaf/a1111-sd-webui-haku-img#4]
Error loading script: main.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-haku-img/scripts/main.py", line 12, in <module>
    from hakuimg import(
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-haku-img/hakuimg/pixel.py", line 88, in <module>
    ) -> tuple[NDArray[Any], NDArray[Any]]:
TypeError: 'type' object is not subscriptable

**Comment by KohakuBlueleaf** [comment]
What is your python version?
This extension can only run in python>=3.10

**Comment by vannoo67** [comment]
I have the same problem. 
I have Python 3.10.9 installed, but webui (installed using the standard method for Linux) appears to run a local version of Python 3.8.10. Any tips on how to change this?

**Comment by KohakuBlueleaf** [comment]
@vannoo67 you need to rebuild the venv

**Comment by vannoo67** [comment]
Thanks for this.

If anyone else is struggling with this issue, this is how I solved the problem. 
Not sure if this is how it is supposed to go, it was a bit hacky, but it worked for me.

Bare in mind that my python3.10 installation was compiled from source and setup as an alt-install.
I still have a python3.8 installation in the system (maybe that is what complicated this for me)
I have aliases in my .bashrc to point both python and python3 to python3.10

$ python --version
Python 3.10.9

$ cd ~/stable-diffusion-webui

I rebuilt the venv using the current python version
$ python -m venv venv
$ source venv/bin/activate

Testing which python was current showed that it was still seeing 3.8.10
(venv) $ which python
/home/jon/stable-diffusion-webui/venv/bin/python
(venv) $ python --version
Python 3.8.10

(venv) $ ls -l ls -l venv/bin
...
lrwxrwxrwx 1 jon jon    7 Jan 24 15:05 python -> python3
lrwxrwxrwx 1 jon jon   25 Jan 24 15:05 python3 -> /usr/bin/python3
lrwxrwxrwx 1 jon jon   25 Jan 25 16:05 python3.10 -> /usr/local/bin/python3.10
...

So I changed the python3 sym-link to point to my python3.10 installation
(venv) $ cd venv/bin
(venv) $ rm python3
(venv) $ ln -s /usr/local/bin/python3.10 python3
(venv) $ deactivate

$ cd ~/stable-diffusion-webui
$ ./webui.sh
...
################################################################
Launching launch.py...
################################################################
Python 3.10.9 (main, Jan 25 2023, 16:54:51) [GCC 9.4.0]
...

Webui identified the correct python version, then proceeded to download and install the dependencies again (into the new python3.10 library)

This left the old python3.8 lib lying around, so I deleted it
$ rm -rf ~/stable-diffusion-webui/venv/lib/python3.8

Incidentally, I had an issue with a "ModuleNotFoundError: No module named '_lzma' " error, which related to a missing dependency when I compiled Python3.10.9.

Installing the lzma library then recompiling Python3.10.9 solved this problem.
$ sudo apt install liblzma-dev
$ // install python from source

**Comment by vannoo67** [comment]
I've now had a chance to play with HakuImg.
What a fabulous tool. Thanks so much for contributing it to the community.

**Comment by KohakuBlueleaf** [comment]
@vannoo67 So glad you can figure it out!
don't forget to update to latest
I have added some new features like 16 different blending mode

**Comment by KohakuBlueleaf** [comment]
@vannoo67  @umairsali07 
I have updated for py3.8/3.9 user
