### ISSUE TITLE
No module named 'modules.ui_components

### ISSUE THREAD

**Issue by TechnoClasher** [KohakuBlueleaf/a1111-sd-webui-haku-img#8]
Traceback (most recent call last):
  File "E:\ai\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "E:\ai\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "E:\ai\stable-diffusion-webui\extensions\a1111-sd-webui-haku-img\scripts\main.py", line 7, in <module>
    from modules.ui_components import FormRow
ModuleNotFoundError: No module named 'modules.ui_components'

I checked the other repo which is marked as "read this", my python version isn't the problem according to me as its already 3.10.9, and venv is using that.

**Comment by KohakuBlueleaf** [comment]
Your sd-webui version is too old to use this extension, sorry QQ.
Maybe try update to the latest version.

**Comment by TechnoClasher** [comment]
ah got it

**Comment by TechnoClasher** [comment]
fixed it. Thanks for telling me that its outdated, I thought it was updated as I made sure that it gets updated everytime i launch but for some reason it wasn't getting merged locally. Thanks again :D

**Comment by KohakuBlueleaf** [comment]
:D enjoy
