### ISSUE TITLE
what about an image rotator?

### ISSUE THREAD

**Issue by gsgoldma** [KohakuBlueleaf/a1111-sd-webui-haku-img#9]
sometimes it would be cool to generate some things and turn them upside down since stable diffusion doesn't do sideways or upside orientations very easily.

**Comment by KohakuBlueleaf** [comment]
Good one
Will add it

**Comment by CuteCat1111** [comment]
@KohakuBlueleaf 
Is flip image feature still planned?

**Comment by KohakuBlueleaf** [comment]
> @KohakuBlueleaf Is flip image feature still planned?

Yeah
I am busy in the end of the semester in college these days

Will impl this in this weekend or next week

If you want to do it you can just pr it
